# Data preprocessing - dáta **dotácie**

Možno sa ukáže, že tento notebook nepotrebujeme... Len som nechcela mazať Romanu robotu

V tomto notebooku si načítame dáta o dotáciách, upravíme ich do slušnej formy pre ďalšie analýzy a následne uložíme v tejto upravenej forme do excelu/csv.

In [1]:
import pandas as pd

## Načítanie dát

* súbory majú príponu `xls` pre roky 2008 - 2012, inak majú `xlsx`

In [64]:
nazvy = []
for y in range(2008, 2013):
    nazvy.append(f"../data/dotacie{y}.xls")
for y in range(2013, 2023):
    nazvy.append(f"../data/dotacie{y}.xlsx")

In [65]:
nazvy

['../data/dotacie2008.xls',
 '../data/dotacie2009.xls',
 '../data/dotacie2010.xls',
 '../data/dotacie2011.xls',
 '../data/dotacie2012.xls',
 '../data/dotacie2013.xlsx',
 '../data/dotacie2014.xlsx',
 '../data/dotacie2015.xlsx',
 '../data/dotacie2016.xlsx',
 '../data/dotacie2017.xlsx',
 '../data/dotacie2018.xlsx',
 '../data/dotacie2019.xlsx',
 '../data/dotacie2020.xlsx',
 '../data/dotacie2021.xlsx',
 '../data/dotacie2022.xlsx']

* `sheet_name=None` načíta všetky hárky zo súboru do dictionary, kde values sú dataframe-y a keys sú názvy hárkov

... well to nie je pravda, keys su roky a values su nejake divne slovniky ...

In [66]:
# toto nie je zatial uplne to, co chceme
# TODO

dotacie = {}

for i, file_name in enumerate(nazvy):
    dotacie[i+2008] = pd.read_excel(file_name, sheet_name=None)
#tuto ma problem s nejakymi datumami

/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D24 is marked as a date but the serial value 6343450 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D43 is marked as a date but the serial value 6975100 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell F44 is marked as a date but the serial value 7950880 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4389595 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D43 is marked as a date but the serial value 8878115 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4298228 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D43 is marked as a date but the serial value 8318468 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell C77 is marked as a date but the serial value 25107902.024399996 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D77 is marked as a date but the serial value 29182660.2 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4956630 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 4298228 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D46 is marked as a date but the serial value 8215407 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell C77 is marked as a date but the serial value 27232114.670799997 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D77 is marked as a date but the serial value 32441146.875 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4728948 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 4956630 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D46 is marked as a date but the serial value 8323404 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell C77 is marked as a date but the serial value 27905737.516799994 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D77 is marked as a date but the serial value 32225707.125 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 5343925 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D46 is marked as a date but the serial value 9480900 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 5062100 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 5343925 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D46 is marked as a date but the serial value 9676850 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4851050 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 5062100 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D46 is marked as a date but the serial value 10530350 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4826025 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 4851050 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell F46 is marked as a date but the serial value 9200135 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D23 is marked as a date but the serial value 4946000 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell D26 is marked as a date but the serial value 4826025 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/home/viki/anaconda3/envs/pridav_proj/lib/python3.10/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Cell F46 is marked as a date but the serial value 9822340 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():

In [68]:
display(dotacie[2008]['T2-KN'])
#print(type(dotacie[2008]))

,,Skupina,Študijný odbor,Počet št./uč.,Počet neuč/uč.,Časť platu uč./št.,Časť platu neuč./št.,Prepočet platu neuč./uč.,Príspevok študenta na mzdy vyjadrený ako časť platu učiteľa,Koeficient nákladovosti\n(KN)
0,,NaN,NaN,A,B,C=1/A,D=B/A,E=C*D,F=C+E,G = normalizácia na najmenšiu hodnotu v stĺpci F
1,NaN,1,"lekárske odbory, farmácia, pôrodná asistencia",5,0.6,0.2,0.12,0.108,0.308,4.959322
2,NaN,2,umelecké odbory vrátane dizajnu,4,0.3,0.25,0.075,0.0675,0.3175,5.112288
3,NaN,3,veterinárne odbory,5,1.3,0.2,0.26,0.234,0.434,6.988136
4,NaN,4,"prírodovedné odbory, informačné technológie",10,0.5,0.1,0.05,0.045,0.145,2.334746
5,NaN,5,poľnohospodársrvo,11,0.8,0.090909,0.072727,0.065455,0.156364,2.51772
6,NaN,6,"architektúra, prekladateľstvo, tlmočníctvo",8,0.2,0.125,0.025,0.0225,0.1475,2.375
7,NaN,7,"pedagogické odbory, učiteľstvo I. st, učiteľst...",10.5,0.25,0.095238,0.02381,0.021429,0.116667,1.878531
8,NaN,8,matematika,10.5,0.4,0.095238,0.038095,0.034286,0.129524,2.085553
9,NaN,9,"ekonomické odbory, manažment, obchod, verejná ...",14,0.25,0.071429,0.017857,0.016071,0.0875,1.408898
10,NaN,10,"humanitné odbory, sociálne odbory",12,0.2,0.083333,0.016667,0.015,0.098333,1.583333
11,NaN,11,právo,19,0.2,0.052632,0.010526,0.009474,0.062105,1
12,NaN,12,"učiteľstvo - prírodné vedy, technické odborné ...",9,0.3,0.111111,0.033333,0.03,0.141111,2.272128
13,NaN,13,učiteľstvo - moderné jazyky,11,0.2,0.090909,0.018182,0.016364,0.107273,1.727273
14,NaN,14,"učiteľstvo - matematika, informatika",10.5,0.25,0.095238,0.02381,0.021429,0.116667,1.878531
15,NaN,15,"učiteľstvo - humanitné odbory, sociálne odbory...",11,0.2,0.090909,0.018182,0.016364,0.107273,1.727273
16,,16,"chemicko-technologické odbory, vybrané hutníck...",6.5,0.6,0.153846,0.092308,0.083077,0.236923,3.814863
17,,17,"ošetrovateľstvo, fyzioterapia, verejné zdravot...",6,0.3,0.166667,0.05,0.045,0.211667,3.408192
18,,18,doktorandské štúdium - medicína,5,0.75,0.2,0.15,0.135,0.335,5.394068
19,,19,"doktorandské štúdium - prírodovedné odbory, te...",8,0.75,0.125,0.09375,0.084375,0.209375,3.371292
20,,20,doktorandské štúdium - ostatné odbory,13,0.45,0.076923,0.034615,0.031154,0.108077,1.740222
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,K,modelový pomer priemerného platu odborných a a...,NaN,NaN,0.9,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,Počet št./adm.,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,Centrálna administratíva do 1800 študentov,58.064516,1,NaN,0.017222,0.0155,0.0155,0.249576
25,NaN,NaN,Centrálna administratíva nad 1800 študentov,70,1,NaN,0.014286,0.012857,0.012857,0.207022
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,1,2,3,4,5,NaN,NaN
28,NaN,NaN,Koeficient formy štúdia,Bakalárské štúdium,Druhý stupeň štúdia,Doktorandské štúdium,Spojite 1+2,Spojite 1+2,NaN,NaN
29,NaN,1,koeficient dennej formy štúdia,1,1.5,3,1,1.5,NaN,NaN
30,NaN,2,koeficient externej formy štúdia - neplatiaci,0.3,0.45,0,0.3,0.45,NaN,NaN
31,NaN,NaN,NaN,0,NaN,,NaN,NaN,NaN,NaN